repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.11.9'
    hooks:
      - id: ruff
        args: [--fix, --respect-gitignore, --exit-zero]
      - id: ruff-format
        args: [--respect-gitignore]
  
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest -q
        language: system
        pass_filenames: false
        always_run: true
      - id: windows-compat-check
        name: Windows Compatibility Pattern Check
        entry: bash scripts/check_windows_patterns.sh
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        description: |
          Fails if forbidden patterns (hardcoded /tmp, os.path, etc.) are found in Python files.

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  - repo: local
    hooks:
      - id: deptry
        name: deptry
        entry: poetry run deptry . --config deptry.toml
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-setuptools
          - pydantic>=2.0.0
        args: [--config-file=.mypy.ini, --no-error-summary, --show-error-codes]