repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.0.292'
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix]

- repo: https://github.com/psf/black
  rev: '23.10.0'
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.7.1'
  hooks:
    - id: mypy
      additional_dependencies:
        - types-requests
        - types-setuptools
        - pydantic>=2.0.0
      args: [--strict, --ignore-missing-imports, --disable-error-code=misc]

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: python -m pytest
      language: system
      pass_filenames: false
      always_run: true 