repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.4'
    hooks:
      - id: ruff-format
        name: ruff-format
      
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.4'
    hooks:
      - id: ruff
        args: [--fix, --ignore=E501]
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-setuptools
          - pydantic>=2.0.0
        args: [--strict, --ignore-missing-imports, --disable-error-code=misc]
  
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest -q
        language: system
        pass_filenames: false
        always_run: true 