# deptry configuration
[tool.deptry]
# Keep all rules active (no global ignore)

# Disable transitive dependency rule for now – we'll revisit later
ignore = ["DEP003"]

# Mark internal package so DEP003 ignores self-imports automatically.
known_first_party = ["namegnome"]

# Specific rule fine-tuning
[tool.deptry.per_rule_ignores]
# Ignore known intentional missing runtime dependency
DEP001 = ["requests", "yaml", "pyyaml"]

# Treat the following packages as intentionally unused (dev-only)
DEP002 = [
  "black",
  "ruff",
  "mypy",
  "pytest",
  "pytest-cov",
  "pre-commit",
  "pytest-asyncio",
  "pytest-mock",
  "respx",
  "deptry",
  "types-requests",
  "types-PyYAML",
  "pydantic-settings",
  "click",
  "nltk",
]

# Silence transitive dependency complaints for these internal modules
DEP003 = ["namegnome", "yaml", "requests"]

[tool.deptry.package_module_name_map]
pyyaml = "yaml" 