repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.292'
    hooks:
      - id: ruff-format
        name: ruff-format
        args: [--check]
      
  - repo: https://github.com/psf/black
    rev: '23.11.0'
    hooks:
      - id: black
        language_version: python3.12
  
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.292'
    hooks:
      - id: ruff
        args: [--fix]
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--strict]
  
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest -q
        language: system
        pass_filenames: false
        always_run: true 